CREATE TABLE IF NOT EXISTS "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submission_id" bigint NOT NULL,
	"type" varchar(20) NOT NULL,
	"status" "status_spptg" NOT NULL,
	"nama_pemilik" varchar(255) NOT NULL,
	"village_id" bigint NOT NULL,
	"owner_user_id" bigint,
	"actor_user_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_created_idx" ON "notifications" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_village_idx" ON "notifications" USING btree ("village_id");
