CREATE TABLE "village_boundaries" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "village_boundaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"village_id" bigint NOT NULL,
	"geom" geometry(polygon,4326) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "village_boundaries_village_id_unique" ON "village_boundaries" USING btree ("village_id");--> statement-breakpoint
CREATE INDEX "village_boundaries_geom_idx" ON "village_boundaries" USING gist ("geom");
