CREATE TYPE "public"."boundary_direction" AS ENUM('Utara', 'Timur', 'Selatan', 'Barat', 'Timur Laut', 'Tenggara', 'Barat Daya', 'Barat Laut');--> statement-breakpoint
CREATE TYPE "public"."coordinate_system" AS ENUM('geografis', 'utm');--> statement-breakpoint
CREATE TYPE "public"."document_category" AS ENUM('KTP', 'KK', 'Kwitansi', 'Permohonan', 'SK Kepala Desa', 'Berita Acara', 'Pernyataan Jual Beli', 'Asal Usul', 'Tidak Sengketa', 'Foto Lahan', 'SPPG', 'Lampiran Feedback', 'Lainnya');--> statement-breakpoint
CREATE TYPE "public"."prohibited_area_type" AS ENUM('Hutan Lindung', 'Tanah Pemerintah', 'Cagar Alam', 'Kawasan Industri', 'Fasum/Fasos', 'Sempadan Sungai', 'Sempadan Pantai', 'Kawasan Rawan Bencana', 'Aset TNI/POLRI', 'Lainnya');--> statement-breakpoint
CREATE TYPE "public"."status_spptg" AS ENUM('SPPTG terdata', 'SPPTG terdaftar', 'SPPTG ditolak', 'SPPTG ditinjau ulang', 'Terbit SPPTG');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('Superadmin', 'Admin', 'Verifikator', 'Kecamatan', 'Viewer');--> statement-breakpoint
CREATE TYPE "public"."user_status" AS ENUM('Aktif', 'Nonaktif');--> statement-breakpoint
CREATE TYPE "public"."validation_status" AS ENUM('Lolos', 'Perlu Perbaikan');--> statement-breakpoint
CREATE TABLE "comments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submission_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submission_id" bigint NOT NULL,
	"type" varchar(20) NOT NULL,
	"status" "status_spptg" NOT NULL,
	"nama_pemilik" varchar(255) NOT NULL,
	"village_id" bigint NOT NULL,
	"owner_user_id" bigint,
	"actor_user_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "overlap_results" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agriculture_land_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submissionId" bigint NOT NULL,
	"prohibitedAreaId" bigint NOT NULL,
	"luas_overlap" double precision NOT NULL,
	"percentage_overlap" double precision,
	"nama_kawasan" varchar(255) NOT NULL,
	"jenis_kawasan" "prohibited_area_type" NOT NULL,
	"intersection_geom" geometry(Polygon,4326),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prohibited_areas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prohibited_areas_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nama_kawasan" varchar(255) NOT NULL,
	"jenis_kawasan" "prohibited_area_type" NOT NULL,
	"sumber_data" varchar(255) NOT NULL,
	"dasar_hukum" text,
	"tanggal_efektif" timestamp NOT NULL,
	"tanggal_unggah" timestamp DEFAULT now() NOT NULL,
	"diunggahOleh" bigint,
	"status_validasi" "validation_status" DEFAULT 'Lolos' NOT NULL,
	"aktif_di_validasi" boolean DEFAULT true NOT NULL,
	"warna" varchar(7) NOT NULL,
	"catatan" text,
	"geom" geometry(Polygon,4326) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "status_history" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "status_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"submissionId" bigint NOT NULL,
	"status_before" "status_spptg" NOT NULL,
	"status_after" "status_spptg" NOT NULL,
	"petugas" bigint NOT NULL,
	"alasan" text,
	"feedback" jsonb,
	"tanggal" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "submission_drafts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submission_drafts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"village_id" bigint,
	"editing_submission_id" bigint,
	"current_step" integer DEFAULT 1 NOT NULL,
	"payload" jsonb NOT NULL,
	"last_saved" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "submissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nama_pemilik" varchar(255) NOT NULL,
	"nik" varchar(16) NOT NULL,
	"alamat" text NOT NULL,
	"nomor_hp" varchar(15) NOT NULL,
	"email" varchar(255) NOT NULL,
	"villageId" bigint NOT NULL,
	"kecamatan" varchar(255) NOT NULL,
	"kabupaten" varchar(255) NOT NULL,
	"luas" double precision NOT NULL,
	"luas_manual" double precision,
	"penggunaan_lahan" varchar(255) NOT NULL,
	"catatan" text,
	"geom" geometry(Polygon,4326),
	"geo_json" jsonb,
	"payload" jsonb,
	"status" "status_spptg" NOT NULL,
	"is_valid" boolean DEFAULT true NOT NULL,
	"tanggal_pengajuan" timestamp NOT NULL,
	"owner_user_id" bigint,
	"verifikator" bigint NOT NULL,
	"riwayat" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"feedback" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "submissions_documents" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "document_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"filename" varchar(255) NOT NULL,
	"file_type" varchar(50) NOT NULL,
	"size" integer NOT NULL,
	"url" text NOT NULL,
	"category" "document_category" NOT NULL,
	"submissionId" bigint,
	"draftId" bigint NOT NULL,
	"uploadedBy" bigint NOT NULL,
	"is_temporary" boolean DEFAULT true NOT NULL,
	"uploaded_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"nama" varchar(255) NOT NULL,
	"clerk_user_id" varchar(255),
	"nip_nik" varchar(20) NOT NULL,
	"email" varchar(255) NOT NULL,
	"peran" "user_role" NOT NULL,
	"assigned_village_id" bigint,
	"assigned_kecamatan" varchar(255),
	"status" "user_status" DEFAULT 'Aktif' NOT NULL,
	"nomor_hp" varchar(15),
	"terakhir_masuk" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_clerk_user_id_unique" UNIQUE("clerk_user_id")
);
--> statement-breakpoint
CREATE TABLE "villages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "villages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"kode_desa" varchar(20) NOT NULL,
	"nama_desa" varchar(255) NOT NULL,
	"nama_kepala_desa" varchar(255),
	"juru_ukur_nama" varchar(255),
	"juru_ukur_jabatan" varchar(255),
	"juru_ukur_instansi" varchar(255),
	"juru_ukur_nomor_hp" varchar(20),
	"kecamatan" varchar(255) NOT NULL,
	"kabupaten" varchar(255) NOT NULL,
	"provinsi" varchar(255) NOT NULL,
	"jumlah_pengajuan" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "comments_submission_idx" ON "comments" USING btree ("submission_id");--> statement-breakpoint
CREATE INDEX "notifications_created_idx" ON "notifications" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "notifications_village_idx" ON "notifications" USING btree ("village_id");--> statement-breakpoint
CREATE INDEX "prohibited_areas_geom_idx" ON "prohibited_areas" USING gist ("geom");--> statement-breakpoint
CREATE INDEX "submission_drafts_village_idx" ON "submission_drafts" USING btree ("village_id");--> statement-breakpoint
CREATE INDEX "submissions_geom_idx" ON "submissions" USING gist ("geom");--> statement-breakpoint
CREATE INDEX "submissions_owner_user_idx" ON "submissions" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX "submissions_village_idx" ON "submissions" USING btree ("villageId");--> statement-breakpoint
CREATE INDEX "users_assigned_village_idx" ON "users" USING btree ("assigned_village_id");