CREATE TABLE "audit_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"actor_id" bigint,
	"actor_nama" varchar(255) NOT NULL,
	"actor_email" varchar(255) NOT NULL,
	"actor_peran" varchar(32) NOT NULL,
	"aksi" varchar(128) NOT NULL,
	"entitas" varchar(64) NOT NULL,
	"entitas_id" bigint,
	"ringkasan" text NOT NULL,
	"sebelum" jsonb,
	"sesudah" jsonb,
	"hasil" varchar(16) DEFAULT 'sukses' NOT NULL,
	"galat" text,
	"ip_address" varchar(64),
	"user_agent" varchar(512),
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_idx" ON "audit_logs" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "audit_logs_aksi_idx" ON "audit_logs" USING btree ("aksi");--> statement-breakpoint
CREATE INDEX "audit_logs_entitas_idx" ON "audit_logs" USING btree ("entitas","entitas_id");