CREATE TABLE "page_visits" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "page_visits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"waktu" timestamp DEFAULT now() NOT NULL,
	"path" varchar(255) NOT NULL,
	"ip" varchar(45),
	"rujukan_jenis" varchar(20) NOT NULL,
	"rujukan_host" varchar(255),
	"browser" varchar(60) NOT NULL,
	"os" varchar(60) NOT NULL,
	"perangkat" varchar(20) NOT NULL,
	"negara" varchar(80),
	"kota" varchar(120),
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "page_visits_waktu_idx" ON "page_visits" USING btree ("waktu");